# Generated by Django 2.2.5 on 2019-09-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
