# Generated by Django 2.2.5 on 2019-09-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
