# Generated by Django 2.2.5 on 2019-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='text',
            field=models.CharField(default='toto', max_length=255),
        ),
        migrations.AlterField(
            model_name='likes',
            name='title',
            field=models.CharField(default='toto', max_length=255),
        ),
    ]
