# Generated by Django 2.2.5 on 2019-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_likesd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='toto', max_length=255)),
                ('text', models.CharField(default='toto', max_length=255)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
