# Generated by Django 2.2.5 on 2019-09-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
