# Generated by Django 2.2.5 on 2019-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0011_likes_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
