# Generated by Django 2.2.5 on 2019-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0013_likes_and_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost_Likes_Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('dislikes', models.CharField(max_length=100)),
            ],
        ),
    ]
