# Generated by Django 2.2.5 on 2019-09-15 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0015_leaveacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost_likes_dislikes',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='dislikes',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='likes',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
