# Generated by Django 2.2.5 on 2019-09-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0016_auto_20190915_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpost_likes_dislikes',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='newpost_likes_dislikes',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
