# Generated by Django 2.2.5 on 2019-09-27 19:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0018_auto_20190927_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('test', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
