# Generated by Django 2.2.5 on 2019-09-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0020_auto_20190929_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost_likes_dislikes',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
