# Generated by Django 2.2.5 on 2019-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0021_newpost_likes_dislikes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='count',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
