# Generated by Django 2.2.5 on 2019-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0022_auto_20190930_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='author',
            field=models.CharField(default='toto', max_length=100),
        ),
        migrations.AlterField(
            model_name='count',
            name='title',
            field=models.CharField(default='toto', max_length=255),
        ),
    ]
