# Generated by Django 2.2.5 on 2019-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0023_auto_20190930_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='toto', max_length=100)),
                ('title', models.CharField(default='toto', max_length=255)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='count',
            name='author',
        ),
        migrations.RemoveField(
            model_name='count',
            name='title',
        ),
    ]
