# Generated by Django 2.2.5 on 2019-09-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0024_auto_20190930_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
