# Generated by Django 2.2.5 on 2019-09-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0027_auto_20190930_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
