# Generated by Django 2.2.5 on 2019-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0028_delete_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
