# Generated by Django 2.2.5 on 2019-09-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0029_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
