# Generated by Django 2.2.5 on 2019-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0030_testlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost_likes_dislikes',
            name='tags',
            field=models.CharField(default=['Python'], max_length=200),
        ),
    ]
