# Generated by Django 2.2.5 on 2019-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0031_newpost_likes_dislikes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='tags',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
