# Generated by Django 2.2.5 on 2019-10-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0032_auto_20190930_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='tags',
            field=models.CharField(default='Python', max_length=200),
        ),
    ]
