# Generated by Django 2.2.5 on 2019-10-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0033_auto_20191001_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='tags',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
