# Generated by Django 2.2.5 on 2019-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0034_auto_20191001_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likesd',
        ),
        migrations.AlterField(
            model_name='newpost_likes_dislikes',
            name='tags',
            field=models.CharField(default='Python', max_length=200),
        ),
    ]
