# Generated by Django 2.2.5 on 2019-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0035_auto_20191005_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost_likes_dislikes',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
