# Generated by Django 2.2.5 on 2019-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0036_newpost_likes_dislikes_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveacomment',
            name='status_comment',
            field=models.BooleanField(default=False),
        ),
    ]
